server:
  port: 18888
  
spring:
  datasource:
    mid:
      jdbc-url: jdbc:postgresql://172.16.10.3:15432/city-manage-mid?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: postgres
      password: dgchinapgsql@171026
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 570000  #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
    feature:
      jdbc-url: jdbc:postgresql://10.6.37.9:5432/city-feature-data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: postgres
      password: dgchinapgsql@171026
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 570000  #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      
  redis:
    database: 1
    host: 172.16.10.8
    password:
    port: 16379
    timeout: 5000       # 连接超时时间 单位 ms（毫秒）
#    cluster:
#      nodes: 10.3.1.4:7000,10.3.1.4:7001,...,10.3.1.4:7008
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  # 连接池中的最大空闲连接 默认 8
        min-idle: 0  # 连接池中的最小空闲连接 默认 0
        
mybatis-plus:
  global-config:
    refresh: true
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 30
  client:
    registryFetchIntervalSeconds: 30

logging:
  config: classpath:log4j2-prod.xml
#多网卡环境，指定注册IP
#eureka:
#  instance:
#    ipAddress: 192.168.18.128
# nginx配置 restapi > https://restapi.amap.com
# nginx配置 report > https://report.amap.com
# nginx配置 aqi > http://120.92.60.137:5080
amap:
  cfyddl: http://report.amap.com/detailx/ajax/fcRoadList.do?type=1&adcode=220100 #常发拥堵道路
  mrjtyc: http://report.amap.com/ajax/getCityRoadTop.do?adcode=220100 #明日交通预测
  jtydqs: http://report.amap.com/ajax/cityHourly.do?cityCode=220100&dataType=1,https://report.amap.com/ajax/cityDaily.do?cityCode=220100&dataType=1 #过去24小时拥堵指数变化, 过去7天拥堵指数变化
  yzjtyc: http://report.amap.com/ajax/getCityPredict.do?adcode=220100 #未来一周交通预测
