server:
  port: 18885
  
spring:
  datasource:
    mid:
      jdbc-url: jdbc:postgresql://172.18.183.246:15432/city-manage-mid-test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: postgres
      password: dgchinapgsql@171026
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 570000  #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
    feature:
      jdbc-url: jdbc:postgresql://172.18.183.246:15432/city-feature-data-test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: postgres
      password: dgchinapgsql@171026
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 570000  #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
    gis:
      jdbc-url: jdbc:oracle:thin:@47.112.44.6:1521/orcl
      username: gis
      password: gis
      driver-class-name: oracle.jdbc.driver.OracleDriver
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 570000  #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
  servlet:
      multipart:
      maxFileSize: 30MB
      maxRequestSize: 30MB     
  redis:
    database: 3
    host: 172.18.183.246
    password: redis@digital5112
    port: 16379
    timeout: 5000       # 连接超时时间 单位 ms（毫秒）
#    cluster:
#      nodes: 10.3.1.4:7000,10.3.1.4:7001,...,10.3.1.4:7008
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  # 连接池中的最大空闲连接 默认 8
        min-idle: 0  # 连接池中的最小空闲连接 默认 0
  # 配置rabbitMQ
  rabbitmq:
    host: 39.104.101.87
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual

#统一认证用户队列配置
sso-user-queue:
  name: b230a7ff33304d9a933511ca3eaf968d
  aes-salt: /4g6DMwK2apqYT4OARsqMFD6qKLjSULfHYIm3VyS4+PRrOfG41n5Hee3/TF+yGn2pTJwUpsBbCISFCtyHgycuw==

mybatis-plus:
  global-config:
    refresh: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 30
    
logging:
  config: classpath:log4j2-test.xml     
#多网卡环境，指定注册IP
#eureka:
#  instance:
#    ipAddress: 192.168.18.128