server:
  port: 18886

spring:
  datasource:
    mid:
      jdbc-url: jdbc:postgresql://172.16.0.1:5432/city-manage-mid?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: postgres
      password: Dcd_2wsx3EDC
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 570000  #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
    gis:
      jdbc-url: jdbc:oracle:thin:@172.16.0.1:1521/xe
      username: SDE
      password: SDE
      driver-class-name: oracle.jdbc.driver.OracleDriver
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 570000  #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
  servlet:
    multipart:
    maxFileSize: 30MB
    maxRequestSize: 30MB
  redis:
    database: 2
    host: 172.16.0.1
    password: Dcd_2wsx3EDC
    port: 6379
    timeout: 5000       # 连接超时时间 单位 ms（毫秒）
    #    cluster:
    #      nodes: 10.3.1.4:7000,10.3.1.4:7001,...,10.3.1.4:7008
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  # 连接池中的最大空闲连接 默认 8
        min-idle: 0  # 连接池中的最小空闲连接 默认 0


mybatis-plus:
  global-config:
    refresh: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    ipAddress: 39.107.117.228
  client:
    registryFetchIntervalSeconds: 30
    register-with-eureka: true
    fetch-registry: false

logging:
  config: classpath:log4j2-dev.xml
#多网卡环境，指定注册IP
#eureka:
#  instance:
#   ipAddress: 139.107.117.228

#生成excel模版,并保存的服务器以下路径
upfilepath:
  url: /opt/midapps/zhjg-szss/files/
