eureka:
  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 1000
    
#eureka web security
spring:
  profiles:
    active: dev

#eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
#默认30s
#eureka.server.responseCacheUpdateInvervalMs=2000
#eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
#由于启用了evict其实就用不太上改这个配置了
#默认180s
#eureka.server.responseCacheAutoExpirationInSeconds=60
#启用主动失效，并且每次主动失效检测间隔为20s
#eureka.server.eviction-interval-timer-in-ms=20000
