server:
 port: 8880

logging:
  config: classpath:log4j2-dev.xml
  
spring:
  security:
    user:
      name: dev
      password: dev
      
eureka:
  client:
    serviceUrl:
     defaultZone: http://dev:dev@localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false