spring:
  application:
    name: service-config
  profiles:
    active: native,dev
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
          
eureka:
  instance:
    health-check-url-path: /actuator/health   #应用实例的相对运行状况检查URL路径默认为 /info/health
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"   #暴露所有的端点我们可以看到更多的服务实例相关信息，
  endpoint:
    health:
      show-details: ALWAYS   #health endpoint是否必须显示全部细节